# Practical 09

**Aim:** Demonstrate the data science life cycle and perform Univariate, Bivariate and Multivariate analysis on a real-world dataset.

In [1]:
import pandas as pd

df = pd.read_csv("employee.csv")

### 1. Univariate

In [2]:
df["WorkLifeBalance"].describe()

count    1470.000000
mean        2.761224
std         0.706476
min         1.000000
25%         2.000000
50%         3.000000
75%         3.000000
max         4.000000
Name: WorkLifeBalance, dtype: float64

### 2. Bivariate

In [3]:
df[["JobSatisfaction", "EnvironmentSatisfaction"]].describe()

       JobSatisfaction  EnvironmentSatisfaction
count      1470.000000              1470.000000
mean          2.728571                 2.721769
std           1.102846                 1.093082
min           1.000000                 1.000000
25%           2.000000                 2.000000
50%           3.000000                 3.000000
75%           4.000000                 4.000000
max           4.000000                 4.000000

### 3. Multivariate

In [4]:
df[["JobInvolvement", "RelationshipSatisfaction", "EmployeeNumber"]].describe()

       JobInvolvement  RelationshipSatisfaction  EmployeeNumber
count     1470.000000               1470.000000     1470.000000
mean         2.729932                  2.712245     1024.865306
std          0.711561                  1.081209      602.024335
min          1.000000                  1.000000        1.000000
25%          2.000000                  2.000000      491.250000
50%          3.000000                  3.000000     1020.500000
75%          3.000000                  4.000000     1555.750000
max          4.000000                  4.000000     2068.000000